name: Base Automations for Self Hosted K3d Cluster

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - operators/**
      - dashboard/**
      - certificates/**
      - .github/workflows/cluster-base.yml
  pull_request:
    paths:
      - operators/**
      - dashboard/**
      - certificates/**
      - .github/workflows/cluster-base.yml
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

concurrency:
  cancel-in-progress: false
  group: cluster-base

jobs:
  operators_deploy:
    name: Operators Deployment onto Self Hosted K3d Cluster
    uses: PhotoAtom/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: Operators
      folder_path: operators
      runners: photoatom
    secrets: inherit

  dashboard_deploy:
    needs: operators_deploy
    name: Kubernetes Dashboard Deployment onto Self Hosted K3d Cluster
    uses: PhotoAtom/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: Kubernetes Dashboard
      folder_path: dashboard
      runners: photoatom
    secrets: inherit

  certificates_deploy:
    needs: dashboard_deploy
    name: Cluster Issuer and MinIO Operator Certificates Deployment onto Self Hosted K3d Cluster
    uses: PhotoAtom/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: Cluster Issuer and MinIO Operator Certificates
      folder_path: certificates
      runners: photoatom
      post_apply_script: |

        # Wait for certs creation
        echo "Waiting for certificates creation"
        kubectl wait --for=condition=Ready=true certificate/sts-certmanager-cert -n minio-operator --timeout=300s
        kubectl wait --for=condition=Ready=true certificate/operator-ca-certificate -n minio-operator --timeout=300s

        # Restart MinIO Operator Deployment
        kubectl rollout restart deployments.apps/minio-operator -n minio-operator
        kubectl rollout status deployments.apps/minio-operator -n minio-operator
    secrets: inherit
