name: Base Automations for Self Hosted K3d Cluster

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - operators/**
      - certificates/**
      - .github/workflows/cluster-base.yml
  pull_request:
    paths:
      - operators/**
      - certificates/**
      - .github/workflows/cluster-base.yml
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

concurrency:
  cancel-in-progress: false
  group: cluster-base

jobs:
  operators_deploy:
    name: Operators Deployment onto Self Hosted K3d Cluster
    uses: PhotoAtom/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: Operators
      folder_path: operators
      runners: photoatom
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

  certificates_deploy:
    needs: operators_deploy
    name: Cluster Issuer and MinIO Operator Certificates Deployment onto Self Hosted K3d Cluster
    uses: PhotoAtom/automations/.github/workflows/tofu-deploy.yml@main
    with:
      deployment_name: Cluster Issuer and MinIO Operator Certificates
      folder_path: certificates
      runners: photoatom
      post_apply_script: |

        # Sleep for some time to give time for certs creation
        echo "Sleeping for 30 seconds to give time for certificates creation"
        sleep 30

        # Restart MinIO Operator Deployment
        kubectl rollout restart deployments.apps/minio-operator -n minio-operator
        kubectl rollout status eployments.apps/minio-operator -n minio-operator
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}

